export const GET_TOTAL_GLOBAL_DATA="GET_TOTAL_GLOBAL_DATA";
export const GET_DAILY_GLOBAL_DATA="GET_DAILY_GLOBAL_DATA";
export const GET_TOTAL_DATA_BY_COUNTRY="GET_TOTAL_DATA_BY_COUNTRY";
export const GET_DAILY_DATA_BY_COUNTRY="GET_DAILY_DATA_BY_COUNTRY";
export const CHANGE_COUNTRY="CHANGE_COUNTRY";
export const GET_RANGE_DATA_BY_COUNTRY="GET_RANGE_DATA_BY_COUNTRY";
export const GET_RANGE_DATA_GLOBAL="GET_RANGE_DATA_GLOBAL";
export const GET_TABLE_DATA="GET_TABLE_DATA";